/*
 * Created on 26 oct. 2015 ( Time 19:14:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fil.persistence.services.fake;

import java.util.List;
import java.util.Map;

import fil.bean.jpa.RessourceEntity;
import fil.persistence.commons.fake.GenericFakeService;
import fil.persistence.services.RessourcePersistence;

/**
 * Fake persistence service implementation ( entity "Ressource" )
 *
 * @author Telosys Tools Generator
 */
public class RessourcePersistenceFAKE extends GenericFakeService<RessourceEntity> implements RessourcePersistence {

	public RessourcePersistenceFAKE () {
		super(RessourceEntity.class);
	}
	
	protected RessourceEntity buildEntity(int index) {
		RessourceEntity entity = new RessourceEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setNom( nextString() ) ;
		entity.setDescription( nextString() ) ;
		entity.setLocalite( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(RessourceEntity entity) {
		log("delete ( RessourceEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(RessourceEntity entity) {
		log("insert ( RessourceEntity : " + entity + ")" ) ;
	}

	public RessourceEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<RessourceEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<RessourceEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<RessourceEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public RessourceEntity save(RessourceEntity entity) {
		log("insert ( RessourceEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<RessourceEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
