/*
 * Created on 26 oct. 2015 ( Time 19:14:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fil.test.persistence;


import org.junit.Assert;
import org.junit.Test;

import fil.bean.jpa.ReservationEntity;
import fil.mock.ReservationEntityMock;
import fil.persistence.PersistenceServiceProvider;
import fil.persistence.services.ReservationPersistence;

/**
 * JUnit test case for Reservation persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class ReservationPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		ReservationPersistence service = PersistenceServiceProvider.getService(ReservationPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Reservation persistence : delete + load ..." );
		
		ReservationPersistence service = PersistenceServiceProvider.getService(ReservationPersistence.class);
		
		ReservationEntityMock mock = new ReservationEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(ReservationPersistence service, ReservationEntityMock mock, Integer id ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		ReservationEntity entity = service.load( id );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( id ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . Utilisateur
			// . Ressource
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( id );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
