/*
 * Created on 26 oct. 2015 ( Time 19:14:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fil.test.persistence;


import org.junit.Assert;
import org.junit.Test;

import fil.bean.jpa.TypeRessourceEntity;
import fil.mock.TypeRessourceEntityMock;
import fil.persistence.PersistenceServiceProvider;
import fil.persistence.services.TypeRessourcePersistence;

/**
 * JUnit test case for TypeRessource persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class TypeRessourcePersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		TypeRessourcePersistence service = PersistenceServiceProvider.getService(TypeRessourcePersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test TypeRessource persistence : delete + load ..." );
		
		TypeRessourcePersistence service = PersistenceServiceProvider.getService(TypeRessourcePersistence.class);
		
		TypeRessourceEntityMock mock = new TypeRessourceEntityMock();
		
		// TODO : set primary key values here 
		//process( service, mock, 0  );
		// process( service, mock, ... );
	}

	//TODO Test non fonctionnel
	private void process(TypeRessourcePersistence service, TypeRessourceEntityMock mock, Integer cle ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		TypeRessourceEntity entity = service.load( cle );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance(  ) ;
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			boolean deleted = service.delete( cle );
			System.out.println("   deleted = " + deleted);
			Assert.assertTrue(deleted) ;
		}		
	}
}
