/*
 * Created on 23 oct. 2015 ( Time 12:09:27 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package fil.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import fil.bean.jpa.ReservationEntity;
import fil.persistence.commons.jpa.GenericJpaService;
import fil.persistence.commons.jpa.JpaOperation;
import fil.persistence.services.ReservationPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Reservation" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class ReservationPersistenceJPA extends GenericJpaService<ReservationEntity, Integer> implements ReservationPersistence {

	/**
	 * Constructor
	 */
	public ReservationPersistenceJPA() {
		super(ReservationEntity.class);
	}

	@Override
	public ReservationEntity load( Integer id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Integer id ) {
		return super.delete( id );
	}

	@Override
	public boolean delete(ReservationEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("ReservationEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
