/*
 * Created on 20 oct. 2015 ( Time 11:40:31 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package fil.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import fil.bean.jpa.TypeResssourceEntity;
import fil.persistence.commons.jpa.GenericJpaService;
import fil.persistence.commons.jpa.JpaOperation;
import fil.persistence.services.TypeResssourcePersistence;

/**
 * JPA implementation for basic persistence operations ( entity "TypeResssource" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class TypeResssourcePersistenceJPA extends GenericJpaService<TypeResssourceEntity, Integer> implements TypeResssourcePersistence {

	/**
	 * Constructor
	 */
	public TypeResssourcePersistenceJPA() {
		super(TypeResssourceEntity.class);
	}

	@Override
	public TypeResssourceEntity load( Integer cle ) {
		return super.load( cle );
	}

	@Override
	public boolean delete( Integer cle ) {
		return super.delete( cle );
	}

	@Override
	public boolean delete(TypeResssourceEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getCle() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("TypeResssourceEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
